### ISSUE TITLE
Перенести аватарки авторов в единую папку

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#108]
Все аватарки будем хранить в отдельной папке. `src/authors/andrey-sitnik.jpg`

- [ ] Перенести все существующие аватарки в папку `src/authors/`.
- [ ] Назвать файлы в формате `имя-фамилия` на латинице.
- [ ] Найти недостающие фотографии в интернете (соблюдая авторские права).
- [ ] Нужно расставить их по сайту как `<img>`, а поверх рисовать шейп с фильтром (на это отдельная задача — #86)

### авторские права
> Я бы пока взял как есть, искать и указывать источники фотографий нужно большим медиа, у нас некоммерческий продукт (пока) небольших масштабов

Это значит, что предпочтительней свободные изображения. Но если будет лучше подходящая несвободная фотография, то просто укажите в коммите откуда её взяли. Очень хорошо, если сразу там же укажете и автора.

**Comment by dariaprikhodko** [comment]
Могу взять себе

**Comment by pepelsbey** [comment]
@dariaprikhodko спасибо :) Начинайте пулреквест с первых правок, зовите на ревью и задавайте вопросы по ходу дела.

**Comment by higimo** [comment]
@dariaprikhodko есть ли какие-то результаты?

**Comment by Holiden** [comment]
Это сделали [тут](https://github.com/web-standards-ru/nouvelle/pull/229). Нужно б закрыть.
