### ISSUE TITLE
Сделать наведение по дизайну

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#123]
![image](https://user-images.githubusercontent.com/105274/68874334-174dc580-0712-11ea-956f-965ec9ed9e03.png)

- Синий: `#0064a4`
- Бирюзовый: `#00abbd`

**Comment by thezaff** [comment]
Создал PR https://github.com/web-standards-ru/nouvelle/pull/124

**Comment by thezaff** [comment]
Я правильно понимаю, что active означает именно состояние (псевдокласс :active), а не focus?
(Просто по-моему опыту многие дизайнеры часто это путают)

**Comment by pepelsbey** [comment]
Да, active — это именно нажатие, про фокус наш дизайнер (да и все остальные) просто не знают (

**Comment by pepelsbey** [comment]
@Holiden можно продолжать :)
