### ISSUE TITLE
Починить семантическую структуру страниц

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#134]
У нас поехала главная структура страницы, даже валидатор ругается. Не доглядел, извините. Должно быть так:

![outline](https://user-images.githubusercontent.com/105274/69013662-d2d15c80-0993-11ea-827e-759e2e5e1138.png)

```html
<header>
    <nav></nav>
</header>
<main>
    <!-- Уникальный контент страницы -->
</main>
<aside></aside>
<footer></footer>
```

Это всё завязано на структуру открывающегося меню за авторством @Holiden, так что я бы наверное поручил ему повернуть меню так, чтобы оно заработало и с этой структурой.

UPD (от @pepelsbey ):
Сейчас у нас примерно вот так и это очень неправильная структура:

```html
<section class="page__navigation">
    <div class="navigation__logo logo"></div>
    <nav class="navigation__bar"></nav>
</section>
<section class="page__content">
    <header class="header">
        <div class="header__logo logo"></div>
        <ul class="header__informer informer"></ul>
    </header>
    <main class="main">
        <article class="preview"></article>
    </main>
    <aside class="links"></aside>
    <footer class="footer"></footer>
</section>
```

Нужно, чтобы было примерно вот так. Не точно так, но с такой вложенностью контента. Мы её в какой-то момент потеряли и теперь нужно вернуть.

```html
<header class="header">
    <div class="page__navigation">
        <div class="navigation__logo logo"></div>
        <nav class="navigation__bar"></nav>
    </div>
    <div class="header__logo logo"></div>
    <ul class="header__informer informer"></ul>
</header>
<main class="main">
    <article class="preview"></article>
</main>
<aside class="links"></aside>
<footer class="footer"></footer>
```

Я понимаю, что это ломает всю структуру блоков и требует большого рефакторинга, но нужно сделать именно так. Если какие-то части потребуют допонительных обёрток для группировки, то это должны быть простые `<div>`, никакие `<section>` за пределами корневых ориентиров страницы появляться не должны.

**Comment by pepelsbey** [comment]
Уточняю задачу. Сейчас у нас примерно вот так и это очень неправильная структура:

```html
<section class="page__navigation">
    <div class="navigation__logo logo"></div>
    <nav class="navigation__bar"></nav>
</section>
<section class="page__content">
    <header class="header">
        <div class="header__logo logo"></div>
        <ul class="header__informer informer"></ul>
    </header>
    <main class="main">
        <article class="preview"></article>
    </main>
    <aside class="links"></aside>
    <footer class="footer"></footer>
</section>
```

Нужно, чтобы было примерно вот так:

```html
<header class="header">
    <div class="page__navigation">
        <div class="navigation__logo logo"></div>
        <nav class="navigation__bar"></nav>
    </div>
    <div class="header__logo logo"></div>
    <ul class="header__informer informer"></ul>
</header>
<main class="main">
    <article class="preview"></article>
</main>
<aside class="links"></aside>
<footer class="footer"></footer>
```

Я понимаю, что это ломает всю структуру блоков и требует большого рефакторинга, но нужно сделать именно так. Если какие-то части потребуют допонительных обёрток для группировки, то это должны быть простые `<div>`, никакие `<section>` за пределами корневых ориентиров страницы появляться не должны.

**Comment by higimo** [comment]
@pepelsbey дополнил текст задачи
