### ISSUE TITLE
Придумать, как зафиксировать уникальные фильтры для аватарок

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#137]
Сейчас при каждой сборке к аватаркам авторов применяется [случайная шейпа и фильтр](https://github.com/web-standards-ru/nouvelle/blob/master/src/pages/index.njk#L18-L19).

```njk
{% set blobColor %}{{ ['teal', 'lightteal', 'moss', 'grass'] | random }}{% endset %}
{% set blobShape %}{{ [1, 2, 3, 4, 5, 6, 7] | random }}{% endset %}

{% for author in collections.people | filterPeople(article.data.author) %}
    <img class="preview__photo
            blob--{{ blobColor }}
            blob--shape-{{ blobShape }}"
        src="/images/author--placeholder.jpg"
        width="113" height="104"
        alt="{{ author.name }}">
    <p class="preview__author">
        <span class="preview__name">{{ author.name }}</span>
    </p>
{% endfor %}
```

Кажется, это будет путать. Лучше бы нам либо придумать алгоритм, который привязывает случайность к псевдониму автора, либо хранить какой-то ключ в профиле. Но первый вариант круче :)

**Comment by ilya-rachinskiy** [comment]
Есть предложение брать остаток отделения  колличества букв  на количество елементов в blob массивах:
```
const blobShapeIndex = people.name.length % blobShape.length ; 
const blobColorIndex = people.url.length % blobColor .length ; 
```

Результат:
```
---
name: Адитья Шридхар
url: https://medium.com/@aditya_sridhar
tags: people
permalink: false
---

const blobShapeIndex = "Адитья Шридхар".length % blobShape.length ;  // 14 % 7 = 0 => blob--shape-1
const blobColorIndex = "https://medium.com/@aditya_sridhar".length % blobColor.length ; // 34 % 4 = 2 =>  blob--moss
```

**Comment by pepelsbey** [comment]
Отличная идея! Это можно попробовать как-нибудь компактно реализовать через [кастомные теги](https://www.11ty.io/docs/custom-tags/#nunjucks-example). Например, зарегистрировать тег `{% blob %}` и передавать туда `author.name`:

```njk
{% for author in collections.people | filterPeople(article.data.author) %}
    <img class="preview__photo {% blob author.name %}"
        src="/images/author--placeholder.jpg"
        width="113" height="104"
        alt="{{ author.name }}">
    <p class="preview__author">
        <span class="preview__name">{{ author.name }}</span>
    </p>
{% endfor %}
```

А всю логику и массивы утащить в тег, но уже на чистом JS. Сделаете пулреквест? Там кажется несложно :)

**Comment by PsarewIvan** [comment]
@ilya-rachinskiy , если отталкиваться от длины строки имени, то есть шанс, что определенные значения фильтров будут чаще повторяться, т.к. длина имени и фамилии примерно плюс/минус будут похожей длины.
Что на счет того, чтобы считать сумму юникод-значений всех символов строки и уже от них брать остаток от деления на длину массива blobshape?
```js
function getIndex(string, array) {
  let index = 0;
  for (let char of string) {
    index += char.charCodeAt(0);
  }
  return index % array.length;
}
const blobShapeIndex = getIndex(people.name, blobShape);
const blobColorIndex = getIndex(people.name, blobColor);
```

**Comment by pepelsbey** [comment]
Самый лучший способ понять — это проверить :) Было бы круто вывести список всех статей с одним способом, с другим и сравнить картинки 😄

**Comment by ilya-rachinskiy** [comment]
Добавил пул #149
