### ISSUE TITLE
Поставить полосу прокрутки на законное место в правой стороне окна

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#144]
Сейчас `body` ограничивается `max-width` и полоса прокрутки сдвигается в нетривиальное место. Интересует это место: https://github.com/web-standards-ru/nouvelle/blob/6fa334a7955a80434c6d2f16e07df50eca8a95bf/src/styles/blocks/page.css#L19

![image](https://user-images.githubusercontent.com/2804205/69626916-a8019b00-105a-11ea-979e-c6d937467ca6.png)

**Comment by higimo** [comment]
@Holiden расскажи, пожалуйста, почему было сделано так в https://github.com/web-standards-ru/nouvelle/commit/15c9f56f8c9f841f4d2bbb1d3682636814336f77#diff-952534d20163950fc753de69ee271bf9R24 ?

**Comment by Holiden** [comment]
> @Holiden расскажи, пожалуйста, почему было сделано так в [15c9f56#diff-952534d20163950fc753de69ee271bf9R24](https://github.com/web-standards-ru/nouvelle/commit/15c9f56f8c9f841f4d2bbb1d3682636814336f77#diff-952534d20163950fc753de69ee271bf9R24) ?

Скорее всего из-за этого. Я могу взять на себя это ишью и посмотреть что будет, если убрать ограничение. Мне кажется, что ничего страшного не должно произойти. 
![57CDED06-9113-4A85-AD0B-5D7E1EA80DB3](https://user-images.githubusercontent.com/48956742/69630506-967eba00-107f-11ea-9b91-45ad16e26f3a.png)

**Comment by higimo** [comment]
@Holiden 
> Я могу взять на себя это ишью

Было бы здорово=) Но лучше бы обсудить с @pepelsbey как он хочет ограничивать максимальную ширину контента. Меня, например, не смущает у каждого блока (`header`, `main`, `aside`, `footer`) указать отдельно. Это учитывает #134

**Comment by Holiden** [comment]
@higimo у меня нет этой проблемы. `max-width` при этом не отключена.

![Аннотация 2019-11-26 235144](https://user-images.githubusercontent.com/48956742/69654696-c93ca880-10a7-11ea-93ad-f8b287fe2ce1.png)

**Comment by higimo** [comment]
@Holiden всё в порядке, я неправильно спулился
