### ISSUE TITLE
Сделать ссылку на главную из лого всегда чёрной и без подчёркивания

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#145]
http://localhost:8080/articles/critical-css/

![image](https://user-images.githubusercontent.com/2804205/69627600-024f2b80-105c-11ea-97e6-68a680485a9f.png)

**Comment by Holiden** [comment]
@higimo может быть у вас не обновлен мастер? Я убирал это.
![Аннотация 2019-11-26 234829](https://user-images.githubusercontent.com/48956742/69654395-4f0c2400-10a7-11ea-92a6-4fbe56cea002.png)
![Аннотация 2019-11-26 234922](https://user-images.githubusercontent.com/48956742/69654432-621ef400-10a7-11ea-8361-01b5f5f69a5b.png)

**Comment by higimo** [comment]
@Holiden всё в порядке, я неправильно спулился
