### ISSUE TITLE
Подготовка сайта к продакшену (сжатие CSS, HTML, JS)

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#164]
Необходимо подготовить сайт к продакшену. `npm run build`
- [ ] Обработать папку dist
- [ ] Сжать css, js, html (map и прочее не требуется)
- [ ] Картинки не жать — на это отдельная задача

## Варианты решения

1. npm-пакеты
2. CSSO + что-то там ещё
3. Parcel
4. Gulp
5. Webpack
6. ????

**Comment by pepelsbey** [comment]
Пример решения: [gulpfile.js](https://github.com/lp-cast/3lp.11ty/blob/master/gulpfile.js) и [package.json](https://github.com/lp-cast/3lp.11ty/blob/master/package.json).

1. build запускает 11ty и собирает сайт в dist
2. pack запускает оптимизацию всего в dist

Но наверное можно и на npm-скриптах такое завести. Но это будут слишком длинные однострочкники. Мне почему-то кажется, что сюда идеально подойдёт [Parcel](https://parceljs.org/).

**Comment by ogonkov** [comment]
@pepelsbey Короч парсель жрёт прям всё что видит, в том числе html примеров из статьи про кроссбраузерные скруглённые уголки

**Comment by pepelsbey** [comment]
Сделал [решение на Gulp](https://github.com/web-standards-ru/nouvelle/pull/171), пока оно кажется ближе всего к нужному.

**Comment by ogonkov** [comment]
Сделал [решение через Webpack](https://github.com/web-standards-ru/nouvelle/pull/172), без волшебных регулярок по html
