### ISSUE TITLE
Не копируются все необходимые файлы

### ISSUE THREAD

**Issue by ogonkov** [web-standards-ru/nouvelle#165]
В сборку не попадают:
- [x] архив с примером для статьи "Как воспитать дизайнера" (`src/articles/coder-vs-designer/example.zip`)
- [x] примеры из "Кроссбраузерные закруглённые уголки" (`src/articles/cross-browser-rounded-corners/demos`)
- [x] gif из "Критический CSS + прогрессивный CSS = ?" (`src/articles/critical-and-progressive-css/images`)

Картинки пропали:
- [x] в статье "Сколько стоит JavaScript?" пропали картинки с 8.png по 16.png

Битая ссылка
- [x] на ютуб видос в "Не проверив HTML5-кода, не суйся в воду — с Майком™ Смитом" (`src/articles/check-it-before-you-wreck-it/index.md`)

**Comment by higimo** [comment]
@ogonkov как воспроизвести? Куда должен попадать, какое действие вообще выполняется? В каком режиме работаете? Что должно быть сделано по итогу?

**Comment by ogonkov** [comment]
> как воспроизвести?

собрать проект
перейти в указанную статью
нажать на ссылку с архивом

> Куда должен попадать, какое действие вообще выполняется?

должен попадать в папку, которая выкладывается публично

> В каком режиме работаете?
```
npm run build
```

> Что должно быть сделано по итогу?

работающая статья

**Comment by pepelsbey** [comment]
> src/articles/the-cost-of-javascript/index.md
> куда-то делось 8 картинок

Оригиналы здесь https://medium.com/web-standards/the-cost-of-javascript-a51051b3fde6
