### ISSUE TITLE
Не показываются изображения авторов.

### ISSUE THREAD

**Issue by wsjscss** [web-standards-ru/nouvelle#170]
**Устройство**: iPhone SE iOs 13.3
**Браузер**: Safari, Chrome

**Проблема**: Не показываются изображения авторов.

Если убрать `-webkit-clip-path` - то проблема исчезает, но картинки не обрезанные

![photo_2020-02-21 13 14 51](https://user-images.githubusercontent.com/20801385/75030190-452e6d00-54ac-11ea-95e4-c01f6ce56e33.jpeg)

**Comment by PsarewIvan** [comment]
Интересно, я проверял на ios, все работало. Сегодня вечером гляну, поправлю

**Comment by pepelsbey** [comment]
Там всякие сложности с SVG-масками, так что я допускаю, что может сломаться.

**Comment by PsarewIvan** [comment]
Исправил это в #173 
На будущее, думаю стоит добавить что-то вроде проверки на наличие автора в базе, при добавлении новой статьи.

**Comment by pepelsbey** [comment]
Хм, а это точно исправляет этот баг? Кажется дело было в clip-path, а не в отсутствии картинок.

**Comment by PsarewIvan** [comment]
В article-card.njk есть такой код:
```
{% for author in collections.people | filterPeople(article.data.author) %}
       <a class="
            article-card__author
            article-card__author{{ articleType }}
            article-card__author{{ featuredClass }}"
            href="{{ author.url }}">
            {{ author.name }}
        </a>

        {% if not featured %}
            <img class="
                    article-card__picture
                    article-card__picture{{ articleType }}
                    {% blob author.name %}"
                src="/images/author--placeholder.jpg"
                width="80" height="74"
                alt="{{ author.name }}">
        {% endif %}
{% endfor %}
```
Цикл просто не находил авторов в коллекции и не создавал ссылку с картинкой.
Сейчас все в порядке:
<img width="666" alt="Снимок экрана 2020-02-24 в 8 10 36" src="https://user-images.githubusercontent.com/28845333/75130067-61652080-56dd-11ea-98c4-ba2a2b72b656.png">

**Comment by pepelsbey** [comment]
@wsjscss аватарки починились с этой правкой?

**Comment by pepelsbey** [comment]
Прямо сейчас у меня не отображаются аватарки в узком окне Safari, а в широком всё нормально:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/105274/76392955-9c28b300-6383-11ea-8796-ad13a58bf54b.png">

Нам то ли нужно сменить систему раскрашивания аватарок, то ли даже не знаю.

**Comment by pepelsbey** [comment]
@yoksel, есть идеи? (

**Comment by pepelsbey** [comment]
Дело точно не в путях к картинкам, это именно беда рендеринга.

**Comment by pepelsbey** [comment]
Например, Фигма показывает вот такой код:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/105274/76393195-19542800-6384-11ea-933e-f31415e91cca.png">

**Comment by yoksel** [comment]
Картинки возвращаются на место, если у `.navigation__logo` отключить `position: fixed;` о_0

**Comment by pepelsbey** [comment]
@yoksel как думаешь, может лучше переделать с blend-mode?

**Comment by yoksel** [comment]
Теоретически можно (хотя потребуются дополнительные обёртки для картинки), но проблема не с фильтрами, а с `clip-path`, фильтры работают

**Comment by wsjscss** [comment]
Ещё вариант: 
```css
// Добавляем visibility: hidden только для экранов ниже 769рх
.navigation__menu {
  ...
  visibility: hidden;
}

@media (min-width: 769px){
  .navigation__menu {
    ...
    visibility: visible;
  }
}

// Когда меню открыто, меняем hidden на visible
.page__body--active .navigation__menu {
  visibility: visible;
}
```
@pepelsbey Витал в переписке что вы собираетесь избавиться от этого эффекта, тогда и баг пропадёт сам.

**Comment by pepelsbey** [comment]
@wsjscss да, но лучше бы нам какой-нибудь хотфикс, пока дизайн не доделан. Пулреквест? :)

**Comment by Holiden** [comment]
Это сделали [тут](https://github.com/web-standards-ru/nouvelle/pull/253). @pepelsbey нужно б закрыть?
