### ISSUE TITLE
Логотип перекрывает меню при наведении

### ISSUE THREAD

**Issue by AndrewLosseff** [web-standards-ru/nouvelle#176]
При наведении курсора на логотип на странице "Статьи" слово  "Веб-стандарты" перекрывает первый пункт меню.

![Screen Shot 2020-02-29 at 2 18 03 PM](https://user-images.githubusercontent.com/10829539/75607333-a1be0780-5afe-11ea-9937-64b2708c09ff.png)

браузеры: Firefox 74.0b9, Safari 13.0.5 (15608.5.11)
разрешение: 1440x768

**Comment by pepelsbey** [comment]
Вероятное решение: подобрать ширину, при которой прятать меню под кнопку, как только лого в наведённом состоянии становится в опасной близости.

**Comment by ogonkov** [comment]
Либо можно сделать флекс, который будет переезжать на вторую строку, если ему не хватает ширины, и будет скрываться в тумане overflow hidden

**Comment by pepelsbey** [comment]
Нет, в этом доме мы не скрываем контент ради визуальных эффектов :) Да и вообще — не скрываем. Так что нужно просто подобрать брейкпоинт.

**Comment by AndrewLosseff** [comment]
Предлагаю решение: не увеличивать так сильно логотип при наведении
Гипотеза: для пользователя меню важнее чем крупный логотип

**Comment by alkorlos** [comment]
Ширина при которой придется прятать меню под кнопку - 1550px, сейчас меню прячется под кнопку на 1024px.
Последняя контрольная точка увеличивающая размер логотипа 1440px, можно заменить её на 1550px, а на 1440px добавить еще один промежуточный размер логотипа, при котором он не будет перекрывать меню.
Код сделал, вроде получается неплохо, если такой вариант решения подходит, добавлю пулреквест.

**Comment by pepelsbey** [comment]
@alkorlos давайте как вы предлагаете, спасибо!
