### ISSUE TITLE
Карточка статьи. Буквица очень странная

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#181]
Она кажется слишком мелкой и всего на пару пикселей вылезает за строку — это неприемлемо.

![image](https://user-images.githubusercontent.com/2804205/76346088-7ebd0000-6315-11ea-9633-3229e69c9a1f.png)

**Comment by pepelsbey** [comment]
То есть не по дизайну, там она ровно в две строки.

**Comment by alkorlos** [comment]
Готово.

**Comment by alkorlos** [comment]
Готово.
