### ISSUE TITLE
Главная страница. Поставить ссылку на конференцию

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#182]
Как пользователю этот баннер абсолютно бесполезен без ссылки. Лучше его вообще убить, если нельзя давать ссылку.

![image](https://user-images.githubusercontent.com/2804205/76346095-811f5a00-6315-11ea-84f4-e49ba629e934.png)

**Comment by PsarewIvan** [comment]
А можно поподробнее почему это не ссылка? У меня сайт собирается и сслыка на конференцию генерируется. Шаблон блока находится в `includes/conference-link.njk`
`<a class="conference-link" href={{ conference.data.url }}>`
Шаблон ссылается на `pages/conference.md` в котором `conference.data.url` в данный момент стоит `#`.

**Comment by higimo** [comment]
Лол, тут бы подчёркивание тогда, я даже не подумалкликнуть и обнаружить
решётку=)

вт, 10 мар. 2020 г., 22:22 Ivan Psarew <notifications@github.com>:

**Comment by PsarewIvan** [comment]
так подчеркивание же есть:
![image](https://user-images.githubusercontent.com/28845333/76351638-d9a72500-631e-11ea-9fbc-8ee4ffd54251.png)

**Comment by pepelsbey** [comment]
Ставить ссылку некуда, блок пока уходит, как и задача.
