### ISSUE TITLE
Карточка статьи. Пофиксить виды ссылок

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#183]
Мы видим два вида ссылок: белая без подчёркивания (прямо как текст над ней, да?) и синяя без подчёркивания. И вообще, вы уверены без тапа, что тег тут кликабелен (это так)?

![image](https://user-images.githubusercontent.com/2804205/76346104-8381b400-6315-11ea-8ca7-df4b6aec30bd.png)

**Comment by pepelsbey** [comment]
Как хотфикс я бы сделал белую ссылку с подчёркиванием в обоих случаях.

**Comment by alkorlos** [comment]
Сейчас получилось так что ссылки на перевод и на тэг на десктопе не видимы, там нет темного фона с мобильного.
![link](https://user-images.githubusercontent.com/14668230/77486823-2a07a200-6e4a-11ea-991b-2bbbd2c7e2bc.jpg)

**Comment by PsarewIvan** [comment]
Ого, как это я так пропустил. Поправлю, постараюсь оперативнее :)
