### ISSUE TITLE
Галерея статей. Не подгружаются аватарки

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#184]
Можно ли это исключить в будущем? Вижу такое в хроме на андроиде

![image](https://user-images.githubusercontent.com/2804205/76346819-b5dfe100-6316-11ea-8299-e17ec18e5d29.png)

**Comment by ogonkov** [comment]
У меня это не работало и в Firefox for Android

Но сейчас внезапно перестало воспроизводиться

**Comment by pepelsbey** [comment]
Эти аватарки просто отсутствуют как данные. Этот скриншот, как я понимаю, сделан в экспериментальной ветке people.

**Comment by MeFoDy** [comment]
Аватарки добавлены в https://github.com/web-standards-ru/nouvelle/pull/229
Для тех, кого не нашёл, будет такая же сетка. Оставляем или заменяем плейсхолдер на что-то другое?

**Comment by pepelsbey** [comment]
Оставляем шашечки
