### ISSUE TITLE
Главное меню. Убрать фокус-состояние у кнопки только для мобильников

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#185]
![image](https://user-images.githubusercontent.com/2804205/76346821-b7110e00-6316-11ea-87db-95d6ca6b0243.png)

**Comment by ogonkov** [comment]
В хроме до сих пор не поддерживается [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)

**Comment by ogonkov** [comment]
Ну и в целом на запуск это не должно влиять, это не баг, я люблю например фокусное состояние во всех его проявлениях

**Comment by pepelsbey** [comment]
Согласен, это можно не привязывать к запуску. А фокус всё-таки выглядит не очень, но это другая задача.

**Comment by ogonkov** [comment]
Хейдона на вас нет(
