### ISSUE TITLE
Главная страница. Ссылка «Все статьи» не считывается как интерфейсная кнопка

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#186]
Её легко принять за фразу «The end», «На этом пока всё».

![image](https://user-images.githubusercontent.com/2804205/76346827-b8423b00-6316-11ea-8eb3-0f4c26ad9c38.png)

**Comment by ogonkov** [comment]
дизайн есть?

**Comment by pepelsbey** [comment]
Давайте её просто подчеркнём

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/105274/76390375-587f7a80-637e-11ea-8c0f-6a33284240b9.png">
