### ISSUE TITLE
Главная страница. Название подкаста надо уметь горизонтально скроллить

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#187]
![image](https://user-images.githubusercontent.com/2804205/76346833-b9736800-6316-11ea-8512-dc735041cbba.png)

**Comment by ogonkov** [comment]
зачем?

**Comment by ogonkov** [comment]
Учитывая что это ссылка, вангую что скролла дело даже не дойдёт, долгий тап откроет контекстное меню

**Comment by pepelsbey** [comment]
Это исправлено в обновлённом дизайне, так что будет перевёрстано. Для запуска это не нужно, информеры выпиливаем.

**Comment by pepelsbey** [comment]
Информеры сейчас выпилены, в новом дизайне они не будут скрывать текст.
