### ISSUE TITLE
Сверстать страницу со списком статей по тегам

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#190]
Сейчас она [выглядит не очень](https://web-standards.dev/articles/tags/js/):

<img width="647" alt="image" src="https://user-images.githubusercontent.com/105274/76390801-1efb3f00-637f-11ea-8a11-d727170b8e2e.png">

Предлагаю за основу взять список статей и вместо года вывести название тега:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/105274/76390832-30444b80-637f-11ea-874d-ebbc3494092b.png">

А в конце вывести «Все теги» таким образом

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/105274/76390872-4225ee80-637f-11ea-8abb-e18d45d3f70f.png">

**Comment by ogonkov** [comment]
Кажется не удобным статьи группировать не хронологически а по тегам

**Comment by Holiden** [comment]
Это сделали [тут](https://github.com/web-standards-ru/nouvelle/pull/219). Нужно б закрыть.
