### ISSUE TITLE
Сверстать страницу с тегами

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#191]
Сейчас она [выглядит не очень](https://web-standards.dev/articles/tags/):

<img width="723" alt="image" src="https://user-images.githubusercontent.com/105274/76390976-76011400-637f-11ea-9f8c-5b67f0342388.png">

Предлагаю за основу взять страницу со статьями и написать там «Теги»

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/105274/76391036-9c26b400-637f-11ea-9f5c-332685f75612.png">

Но вот как именно вывести список — это творческая часть задачи :)

**Comment by MeFoDy** [comment]
Страница есть. Закрываем?

**Comment by pepelsbey** [comment]
Ага
