### ISSUE TITLE
Карточка статьи. Отсутствие переводчика при наличии графы

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#193]
Надо бы убрать графу, если там никого нет. Да и вообще у каких это переводных статей нет переводчика?

Если перевод и редактуру делал один человек, то надо так и писать: «Перевод и редактура Вадима Макеева»

https://web-standards.dev/articles/what-accessibility-taught-me/

**Comment by pepelsbey** [comment]
Переводчик [в оригинале](https://medium.com/web-standards/what-accessibility-taught-me-207d1ff0e80c) есть, просто его не завели.

**Comment by MeFoDy** [comment]
Файл с переводчиком заведён. Закрываем?
