### ISSUE TITLE
Карточка статьи. Уменьшить интерлиньяж

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#195]
https://web-standards.dev/articles/what-accessibility-taught-me/

![image](https://user-images.githubusercontent.com/2804205/76416075-71525500-63ab-11ea-82b0-fefa1a2a713d.png)

**Comment by pepelsbey** [comment]
Потому, что?..

**Comment by alkorlos** [comment]
Видимо потому что у blockquote line-height на десктопе не соответствует дизайну, поставил 1.42 хотя по дизайну должно быть 1.421, но такое значение stylelint не пропускает, наверное правильно делает.
Заодно убрал у blockquote line-height на мобильных так как он дублировал стандартный.
