### ISSUE TITLE
Карточка статьи. Подбить черточки поближе к пунктам списка

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#196]
https://web-standards.dev/articles/what-accessibility-taught-me/

![image](https://user-images.githubusercontent.com/2804205/76416188-a494e400-63ab-11ea-9d8b-6c932bc6c04c.png)

**Comment by pepelsbey** [comment]
В этих около-дизайн-задачах не хватает мотивации: подбить ближе потому, что?.. Например, не соответствует макету. Или аргументировать почему макет неправ.

Иначе за них возьмутся, дойдёт до ревью и выяснится, что так и нужно (

**Comment by alkorlos** [comment]
При наложении дизайна на текущую реализацию получается вот что:
![Карточка статьи  Подбить черточки поближе к пунктам списка](https://user-images.githubusercontent.com/14668230/76709824-4b1a1580-671b-11ea-86db-b7428730b494.jpg)

1. У этой черточки не тот шрифт, по дизайну должен быть Dewi Expanded, а сейчас применяется шрифт по умолчанию - Dewi что дает разницу во внешнем виде.
2. По дизайну расстояние между черточками и пунктами списка нужно наоборот увеличить, сейчас у ol > li::before на больше 1240px отступ слева 6px, по дизайну он должен быть 0. 

Сделать как по дизайну должно быть?

И есть ли какой то договор когда при верстке этого сайта использовать абсолютные единицы, когда относительные? Если говорить об этих черточках сейчас в одном месте позиционирование через em (top: -0.4em;), в другом через px (left: 6px;), наверное лучше к какому то единообразию сразу привести.

**Comment by pepelsbey** [comment]
> Сделать как по дизайну должно быть?

Да!

> когда … абсолютные единицы, когда относительные?

В целом, подход такой: всё в пикселях, кроме ситуаций, когда емы помогут сохранить пропорции какого-то блока при увеличении или уменьшение размера шрифта.

**Comment by alkorlos** [comment]
Текущая задача готова, по спискам еще могу отметить такую ситуацию на мобильном:
![article-list-mobile](https://user-images.githubusercontent.com/14668230/76712362-845d8000-6731-11ea-925e-56b2b38a260f.jpg)

Дизайна нет, но я думаю будет правильно хотя бы сделать одинаковый отступ у разных типов списков и уменьшить размер маркеров нумерованного списка, сделать в рамках этой задачи?

**Comment by pepelsbey** [comment]
@alkorlos, было бы круто! Плюс, если есть начертание потоньше, я бы использовал его — цифры очень тяжёлые получаются.

**Comment by alkorlos** [comment]
Сейчас в figma есть вкладка desktop с дизайном article 1920px и вкладка responsive с дизайнами article 1440px, 375px и 320px.
В дизайне 1920px маркер маркированного списка сделан с помощью шрифта Dewi Expanded, в адаптациях это просто блок 14px на 2px с серым фоном.
В дизайне 1920px маркер нумерованного списка с помощью шрифта сделан Dewi Expanded, в адаптациях с помощью шрифта Dewi.
Конечно можно сделать и так, но выглядит странно.
Например если делать по дизайну то маркер маркированного списка при пункте в одну строку будет находиться между первой и второй строкой:
![article](https://user-images.githubusercontent.com/14668230/76907214-1a72e100-68bf-11ea-9d30-362d9e78c6bb.jpg)
Маркер нумерованного списка в адаптациях сделан более жирным шрифтом чем в десктопе.

В общем вопрос такой - дизайны адаптаций актуальны, по ним делать?

Как раз к "Плюс, если есть начертание потоньше, я бы использовал его — цифры очень тяжёлые получаются."
Сейчас в верстке на 1920px ошибка, там должно быть более тонкое начертание, на мобильных все как раз по дизайну.

**Comment by pepelsbey** [comment]
Я бы нормализовал эти списки, не ориентируясь на дизайн — там много проблем. То есть вот просто взять и принять решение, как лучше. М? :)

**Comment by alkorlos** [comment]
Вопрос и состоял в том доверять ли дизайнам, иногда от них в любом случае нельзя отступать. Хорошо, сделаю ориентируясь на дизайн десктопа, на мобильных посмотрю по ситуации как лучше.
