### ISSUE TITLE
Карточка статьи. Сделать отступ до списка меньше отступа после списка

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#197]
![image](https://user-images.githubusercontent.com/2804205/76416233-bc6c6800-63ab-11ea-8781-9e5414af57e1.png)

**Comment by alkorlos** [comment]
Сделал, но на этой странице в целом не все хорошо с отступами.
Например сейчас между заголовком h2 и параграфом отступ 24px, между параграфами 1em (21px), по дизайну должно быть 22px и 39px соответственно. Остальные элементы тоже хорошо бы проверить.
И, насколько я знаю, предпочтительнее делать всем элементам нижние отступы, на этой странице это правило выполняется к примеру у блока с классами "article__authors authors", в самой статье отступы преимущественно верхние.
Заняться этими проблемами?

**Comment by alkorlos** [comment]
В предыдущий pull request попал код из другой задачи, исправил.

**Comment by alkorlos** [comment]
@pepelsbey Проверить то о чем я в этой задаче 16 марта писал или то что сейчас есть подходит?

**Comment by alkorlos** [comment]
@pepelsbey поскольку работа над сайтом возобновилась спрошу еще раз: может стоит в рамках этой или отдельной задачи перепроверить все стили типографики на странице статьи? Так как несоответствий дизайну больше чем открытых задач, про одно из них выше писал. Или то что сейчас подходит?

**Comment by pepelsbey** [comment]
@alkorlos я бы пока поправил только самые вопиющие дела, а потом уже будем править последовательно по свежему дизайну.

**Comment by alkorlos** [comment]
@pepelsbey не знал что будет свежий дизайн, хорошо, тогда нет смысла все подряд проверять.
