### ISSUE TITLE
Галерея статей. Подлить настоящих фотографий авторов

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#198]
Связана с #108

![image](https://user-images.githubusercontent.com/2804205/76416302-df971780-63ab-11ea-99b3-c304ad5678bb.png)

**Comment by pepelsbey** [comment]
Сделал новую структуру хранения данных авторов, плейсхолдер если нет фотки в #218.

Теперь эту задачу можно делать дальше как «добавить фотки авторов», для неё всё готово.

**Comment by MeFoDy** [comment]
Берусь.

**Comment by pepelsbey** [comment]
Прочитал «Беларусь», удивился!
