### ISSUE TITLE
Сверстать страницу статей

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#2]
- [ ] Статьи. Подключить шапку #62
- [ ] Статьи. Заголовок страницы #63
- [ ] Статьи. Статьи, разбитые по годам #64
- [ ] Статьи. Ссылка на конференцию #65
- [ ] Статьи. Подключить футер #66

----

![Articles](https://user-images.githubusercontent.com/2804205/62827096-4f081700-bbd1-11e9-9700-8ea4dba7bc7a.png)

**Comment by higimo** [comment]
@pepelsbey здесь интересуют детали дизайна. Хотелось бы генерировать эту страницу из какого-то единого списка, если ты одобришь этот подход в #1

Здесь почему-то нет текста аннотации к статьям, это умышленно?

Шапка здесь совсем другая. Это специально? Например, обычно дизайнеры не хотят, чтобы меню скакало от страницы к странице.

Правильно понимаю, что если конфа не планируется, то просто ссылки этой не будет? Взамен (как вариант на будущее) можно предложить подать заявку на выступление в гугл-форму или почту.

**Comment by pepelsbey** [comment]
> Хотелось бы генерировать эту страницу из какого-то единого списка

Коллекция `articles` и есть этот список, просто мы выводим его одним образом на главной, другим — на странице архива статей.

> Здесь почему-то нет текста аннотации к статьям, это умышленно

Всё нарисованное предлагаю считать умышленным и делать именно так. А если кажется, что что-то теряется — предлагать изменить.

> Шапка здесь совсем другая

У нас есть два варианта шапки: одна на главной (с информерами про подкаст, конференцию) и другая на всех остальных страницах.

> Если конфа не планируется, то ссылки не будет

Да, именно так.
