### ISSUE TITLE
Статьи. Сделать выравнивание аватаров на десктопе

### ISSUE THREAD

**Issue by PsarewIvan** [web-standards-ru/nouvelle#214]
Сейчас в списке статей на разрешения выше `1024px` аватар автора выравнивается по нижней границе картинки:
![image](https://user-images.githubusercontent.com/28845333/77529521-d4121900-6ea0-11ea-9d67-76178c0b53da.png)
Предлагаю сделать выравнивание по верхней границе, как в макете:
![image](https://user-images.githubusercontent.com/28845333/77534977-c792be00-6eaa-11ea-9e06-ce48a143d38e.png)

**Comment by pepelsbey** [comment]
Да, пожалуйста :)

**Comment by alkorlos** [comment]
Проблема была в том что когда добавляли ссылку на пользователя на его аватар, забыли дать ссылке класс и перенести нужные стили на ссылку, поэтому выравнивание было верное, проблема была в другом, исправил.
