### ISSUE TITLE
Оттипографить статьи

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#224]
# Процесс

Задачу пока удобно делать только [в типографе Лебедева](https://www.artlebedev.ru/typograf/). Там нужно выставить настройку  внизу. Процесс:

1. Открыть типограф
2. Выставить настройку «Выдавать символы: готовыми символами», сохранить
3. Скопировать текст статьи, за исключением мета-блока
4. Оттипографить, вставить вместо оригинального текста, сохранить.
5. Открыть диф и убедиться, что там нет ошибок и лишних правок.

Что точно поедет:

- Дефисы у списков, двойные дефисы везде
- Отступы, одиночные и двойные кавычки в коде
- Ёлочки иногда зачем-то заменяются на прямые кавычки
- Символы многоточия `…` заменятся на три точки `...`, их нужно вернуть

# Статьи

- [x] [Чему меня научил год изучения и преподавания доступности](https://web-standards.dev/articles/what-accessibility-taught-me/) `/articles/what-accessibility-taught-me/`
- [x] [Введение в вариативные шрифты](https://web-standards.dev/articles/introduction-to-variable-fonts/) `/articles/introduction-to-variable-fonts/`
- [x] [Как русскоязычные пользователи с особыми потребностями пользуются сайтами](https://web-standards.dev/articles/a11y-poll-2019/) `/articles/a11y-poll-2019/`
- [x] [Инклюзивные компоненты: слайдер](https://web-standards.dev/articles/a-content-slider/) `/articles/a-content-slider/`
- [x] [Помимо автоматизированного тестирования доступности: шесть вещей, которые я проверяю на каждом своём сайте](https://web-standards.dev/articles/six-things-i-check/) `/articles/six-things-i-check/`
- [x] [Доступность и закон](https://web-standards.dev/articles/a11y-and-law/) `/articles/a11y-and-law/`
- [x] [Инклюзивные компоненты: сворачиваемые секции](https://web-standards.dev/articles/collapsible-sections/) `/articles/collapsible-sections/`
- [x] [Извлекаем критический CSS](https://web-standards.dev/articles/critical-css/) `/articles/critical-css/`
- [x] [Инклюзивные компоненты: интерфейсы со вкладками](https://web-standards.dev/articles/tabbed-interfaces/) `/articles/tabbed-interfaces/`
- [x] [Инклюзивные компоненты: переключатель темы](https://web-standards.dev/articles/theme-switcher/) `/articles/theme-switcher/`
- [x] [Инклюзивные компоненты: тултипы и тоглтипы](https://web-standards.dev/articles/tooltips-toggletips/) `/articles/tooltips-toggletips/`
- [x] [Инклюзивные компоненты: меню и кнопки меню](https://web-standards.dev/articles/menu-buttons/) `/articles/menu-buttons/`
- [x] [Всё, что нужно знать про ARIA Live Regions](https://web-standards.dev/articles/aria-live-regions/) `/articles/aria-live-regions/`
- [x] [Советы по доступности интерактивных элементов на мобильных устройствах](https://web-standards.dev/articles/mobile-a11y/) `/articles/mobile-a11y/`
- [x] [Инклюзивные компоненты: список дел](https://web-standards.dev/articles/a-todo-list/) `/articles/a-todo-list/`
- [x] [Новые логические свойства в CSS!](https://web-standards.dev/articles/logical-css-props/) `/articles/logical-css-props/`
- [x] [Как быстро создать десктопное приложение на HTML, CSS и JavaScript](https://web-standards.dev/articles/desktop-app/) `/articles/desktop-app/`
- [x] [CSS и JS в состоянии войны: как это остановить](https://web-standards.dev/articles/css-vs-js/) `/articles/css-vs-js/`
- [x] [HTML, CSS и исчезающие точки входа в индустрию](https://web-standards.dev/articles/vanishing-entry-points/) `/articles/vanishing-entry-points/`
- [x] [Как на самом деле работает position: sticky в CSS](https://web-standards.dev/articles/position-sticky/) `/articles/position-sticky/`
- [x] [Что нового в JavaScript 2019](https://web-standards.dev/articles/new-in-js2019/) `/articles/new-in-js2019/`
- [x] [Text-transform и копирование](https://web-standards.dev/articles/text-transform-and-copy/) `/articles/text-transform-and-copy/`
- [x] [«Исправление» списков](https://web-standards.dev/articles/fixing-lists/) `/articles/fixing-lists/`
- [x] [Puppeteer для краулинга страниц сайта и сохранения их в Markdown](https://web-standards.dev/articles/puppeteer-crawl-to-markdown/) `/articles/puppeteer-crawl-to-markdown/`
- [x] [JavaScript: топ тем и фреймворков для изучения в 2019 году](https://web-standards.dev/articles/top-themes-and-frameworks/) `/articles/top-themes-and-frameworks/`
- [x] [Та же история, только с CSS](https://web-standards.dev/articles/css-vs-js-same-story/) `/articles/css-vs-js-same-story/`
- [x] [Инклюзивные компоненты: переключатели](https://web-standards.dev/articles/toggle-buttons/) `/articles/toggle-buttons/`
- [x] [WebP сегодня: зачем и как?](https://web-standards.dev/articles/webp-today/) `/articles/webp-today/`
- [x] [Доступные SVG-иконки с инлайновыми спрайтами](https://web-standards.dev/articles/accessible-svg-icons/) `/articles/accessible-svg-icons/`
- [x] [Просто используйте стили для :focus, чёрт возьми](https://web-standards.dev/articles/just-use-focus/) `/articles/just-use-focus/`
- [x] [Полезные правила доступности, которые останутся в памяти](https://web-standards.dev/articles/pragmatic-a11y-rules/) `/articles/pragmatic-a11y-rules/`
- [x] [Важность уровней заголовков для вспомогательных технологий](https://web-standards.dev/articles/heading-levels/) `/articles/heading-levels/`
- [x] [CSS: новый вид JavaScript](https://web-standards.dev/articles/css-new-kind-of-javascript/) `/articles/css-new-kind-of-javascript/`
- [x] [Функции-декораторы, которые можно написать с нуля](https://web-standards.dev/articles/function-decorators/) `/articles/function-decorators/`
- [x] [Глубокое погружение в ES-модули в картинках](https://web-standards.dev/articles/es-modules-cartoon-dive/) `/articles/es-modules-cartoon-dive/`
- [x] [Руководство для прохождения интервью по фронтенду](https://web-standards.dev/articles/front-end-interview-handbook/) `/articles/front-end-interview-handbook/`
- [x] [О доступности интерфейсов из первых уст](https://web-standards.dev/articles/a11y-users-interview/) `/articles/a11y-users-interview/`
- [x] [Роутинг, бандлинг и ленивая загрузка на Webpack](https://web-standards.dev/articles/multiple-routes-webpack/) `/articles/multiple-routes-webpack/`
- [x] [Промисы на примерах из жизни](https://web-standards.dev/articles/promises-explained/) `/articles/promises-explained/`
- [x] [Сколько стоит JavaScript?](https://web-standards.dev/articles/the-cost-of-javascript/) `/articles/the-cost-of-javascript/`
- [x] [Метрики загрузки страницы](https://web-standards.dev/articles/performance-metrics/) `/articles/performance-metrics/`
- [x] [Генерация HTTP-запросов: Fetch или Axios.js](https://web-standards.dev/articles/fetch-vs-axios/) `/articles/fetch-vs-axios/`
- [x] [Критический CSS + прогрессивный CSS = ?](https://web-standards.dev/articles/critical-and-progressive-css/) `/articles/critical-and-progressive-css/`
- [x] [Как создать адаптивную сетку](https://web-standards.dev/articles/responsive-grid-system/) `/articles/responsive-grid-system/`
- [x] [Невыполненные обещания веб-компонентов](https://web-standards.dev/articles/broken-promise-web-comps/) `/articles/broken-promise-web-comps/`
- [x] [Реализуем пуш-уведомления на фронтенде и бэкенде](https://web-standards.dev/articles/push-front-back/) `/articles/push-front-back/`
- [x] [Обещание бургерной вечеринки](https://web-standards.dev/articles/promise-burger-party/) `/articles/promise-burger-party/`
- [x] [Манифест? А? Что? Зачем?](https://web-standards.dev/articles/manifest-what-why/) `/articles/manifest-what-why/`
- [x] [Улучшение формы комментариев](https://web-standards.dev/articles/enhancing-comment-form/) `/articles/enhancing-comment-form/`

**Comment by Holiden** [comment]
Возьму пока что эти статьи.

> * [ ]  [Помимо автоматизированного тестирования доступности: шесть вещей, которые я проверяю на каждом своём сайте](https://web-standards.dev/articles/six-things-i-check/) `/articles/six-things-i-check/`
> * [ ]  [Доступность и закон](https://web-standards.dev/articles/a11y-and-law/) `/articles/a11y-and-law/`
> * [ ]  [Инклюзивные компоненты: сворачиваемые секции](https://web-standards.dev/articles/collapsible-sections/) `/articles/collapsible-sections/`
> * [ ]  [Извлекаем критический CSS](https://web-standards.dev/articles/critical-css/) `/articles/critical-css/`

**Comment by Holiden** [comment]
Ещё эти:

> * [ ]  [Инклюзивные компоненты: интерфейсы со вкладками](https://web-standards.dev/articles/tabbed-interfaces/) `/articles/tabbed-interfaces/`
> * [ ]  [Инклюзивные компоненты: переключатель темы](https://web-standards.dev/articles/theme-switcher/) `/articles/theme-switcher/`
> * [ ]  [Инклюзивные компоненты: тултипы и тоглтипы](https://web-standards.dev/articles/tooltips-toggletips/) `/articles/tooltips-toggletips/`
> * [ ]  [Инклюзивные компоненты: меню и кнопки меню](https://web-standards.dev/articles/menu-buttons/) `/articles/menu-buttons/`

**Comment by Holiden** [comment]
Ещё:

> * [ ]  [Всё, что нужно знать про ARIA Live Regions](https://web-standards.dev/articles/aria-live-regions/) `/articles/aria-live-regions/`
> * [ ]  [Советы по доступности интерактивных элементов на мобильных устройствах](https://web-standards.dev/articles/mobile-a11y/) `/articles/mobile-a11y/`
> * [ ]  [Инклюзивные компоненты: список дел](https://web-standards.dev/articles/a-todo-list/) `/articles/a-todo-list/`
> * [ ]  [Новые логические свойства в CSS!](https://web-standards.dev/articles/logical-css-props/) `/articles/logical-css-props/`

**Comment by Holiden** [comment]
Ещё:

> * [ ]  [Как быстро создать десктопное приложение на HTML, CSS и JavaScript](https://web-standards.dev/articles/desktop-app/) `/articles/desktop-app/`
> * [ ]  [CSS и JS в состоянии войны: как это остановить](https://web-standards.dev/articles/css-vs-js/) `/articles/css-vs-js/`
> * [ ]  [HTML, CSS и исчезающие точки входа в индустрию](https://web-standards.dev/articles/vanishing-entry-points/) `/articles/vanishing-entry-points/`
> * [ ]  [Как на самом деле работает position: sticky в CSS](https://web-standards.dev/articles/position-sticky/) `/articles/position-sticky/`

**Comment by Holiden** [comment]
Ещё:

> * [ ] [Что нового в JavaScript 2019](https://web-standards.dev/articles/new-in-js2019/) `/articles/new-in-js2019/`
> * [ ]  [Text-transform и копирование](https://web-standards.dev/articles/text-transform-and-copy/) `/articles/text-transform-and-copy/`
> * [ ]  [«Исправление» списков](https://web-standards.dev/articles/fixing-lists/) `/articles/fixing-lists/`
> * [ ]  [Puppeteer для краулинга страниц сайта и сохранения их в Markdown](https://web-standards.dev/articles/puppeteer-crawl-to-markdown/) `/articles/puppeteer-crawl-to-markdown/`

**Comment by Holiden** [comment]
Ещё:

> * [ ]  [JavaScript: топ тем и фреймворков для изучения в 2019 году](https://web-standards.dev/articles/top-themes-and-frameworks/) `/articles/top-themes-and-frameworks/`
> * [ ]  [Та же история, только с CSS](https://web-standards.dev/articles/css-vs-js-same-story/) `/articles/css-vs-js-same-story/`
> * [ ]  [Инклюзивные компоненты: переключатели](https://web-standards.dev/articles/toggle-buttons/) `/articles/toggle-buttons/`
> * [ ]  [WebP сегодня: зачем и как?](https://web-standards.dev/articles/webp-today/) `/articles/webp-today/`

**Comment by Holiden** [comment]
Ещё:

> * [ ]  [Доступные SVG-иконки с инлайновыми спрайтами](https://web-standards.dev/articles/accessible-svg-icons/) `/articles/accessible-svg-icons/`
> * [ ]  [Просто используйте стили для :focus, чёрт возьми](https://web-standards.dev/articles/just-use-focus/) `/articles/just-use-focus/`
> * [ ]  [Полезные правила доступности, которые останутся в памяти](https://web-standards.dev/articles/pragmatic-a11y-rules/) `/articles/pragmatic-a11y-rules/`
> * [ ]  [Важность уровней заголовков для вспомогательных технологий](https://web-standards.dev/articles/heading-levels/) `/articles/heading-levels/`

**Comment by Holiden** [comment]
> # Процесс
> Задачу пока удобно делать только [в типографе Лебедева](https://www.artlebedev.ru/typograf/). Там нужно выставить настройку внизу. Процесс:
> 
> 1. Открыть типограф
> 2. Выставить настройку «Выдавать символы: готовыми символами», сохранить
> 3. Скопировать текст статьи, за исключением мета-блока
> 4. Оттипографить, вставить вместо оригинального текста, сохранить.
> 5. Открыть диф и убедиться, что там нет ошибок и лишних правок.
> 
> Что точно поедет:
> 
> * Дефисы у списков, двойные дефисы везде
> * Отступы, одиночные и двойные кавычки в коде
> * Ёлочки иногда зачем-то заменяются на прямые кавычки
> 
> # Статьи
> * [x]  [Чему меня научил год изучения и преподавания доступности](https://web-standards.dev/articles/what-accessibility-taught-me/) `/articles/what-accessibility-taught-me/`
> * [x]  [Введение в вариативные шрифты](https://web-standards.dev/articles/introduction-to-variable-fonts/) `/articles/introduction-to-variable-fonts/`
> * [x]  [Как русскоязычные пользователи с особыми потребностями пользуются сайтами](https://web-standards.dev/articles/a11y-poll-2019/) `/articles/a11y-poll-2019/`
> * [x]  [Инклюзивные компоненты: слайдер](https://web-standards.dev/articles/a-content-slider/) `/articles/a-content-slider/`
> * [x]  [Помимо автоматизированного тестирования доступности: шесть вещей, которые я проверяю на каждом своём сайте](https://web-standards.dev/articles/six-things-i-check/) `/articles/six-things-i-check/`
> * [x]  [Доступность и закон](https://web-standards.dev/articles/a11y-and-law/) `/articles/a11y-and-law/`
> * [x]  [Инклюзивные компоненты: сворачиваемые секции](https://web-standards.dev/articles/collapsible-sections/) `/articles/collapsible-sections/`
> * [x]  [Извлекаем критический CSS](https://web-standards.dev/articles/critical-css/) `/articles/critical-css/`
> * [x]  [Инклюзивные компоненты: интерфейсы со вкладками](https://web-standards.dev/articles/tabbed-interfaces/) `/articles/tabbed-interfaces/`
> * [x]  [Инклюзивные компоненты: переключатель темы](https://web-standards.dev/articles/theme-switcher/) `/articles/theme-switcher/`
> * [x]  [Инклюзивные компоненты: тултипы и тоглтипы](https://web-standards.dev/articles/tooltips-toggletips/) `/articles/tooltips-toggletips/`
> * [x]  [Инклюзивные компоненты: меню и кнопки меню](https://web-standards.dev/articles/menu-buttons/) `/articles/menu-buttons/`
> * [x]  [Всё, что нужно знать про ARIA Live Regions](https://web-standards.dev/articles/aria-live-regions/) `/articles/aria-live-regions/`
> * [x]  [Советы по доступности интерактивных элементов на мобильных устройствах](https://web-standards.dev/articles/mobile-a11y/) `/articles/mobile-a11y/`
> * [x]  [Инклюзивные компоненты: список дел](https://web-standards.dev/articles/a-todo-list/) `/articles/a-todo-list/`
> * [x]  [Новые логические свойства в CSS!](https://web-standards.dev/articles/logical-css-props/) `/articles/logical-css-props/`
> * [x]  [Как быстро создать десктопное приложение на HTML, CSS и JavaScript](https://web-standards.dev/articles/desktop-app/) `/articles/desktop-app/`
> * [x]  [CSS и JS в состоянии войны: как это остановить](https://web-standards.dev/articles/css-vs-js/) `/articles/css-vs-js/`
> * [x]  [HTML, CSS и исчезающие точки входа в индустрию](https://web-standards.dev/articles/vanishing-entry-points/) `/articles/vanishing-entry-points/`
> * [x]  [Как на самом деле работает position: sticky в CSS](https://web-standards.dev/articles/position-sticky/) `/articles/position-sticky/`
> * [x]  [Что нового в JavaScript 2019](https://web-standards.dev/articles/new-in-js2019/) `/articles/new-in-js2019/`
> * [x]  [Text-transform и копирование](https://web-standards.dev/articles/text-transform-and-copy/) `/articles/text-transform-and-copy/`
> * [x]  [«Исправление» списков](https://web-standards.dev/articles/fixing-lists/) `/articles/fixing-lists/`
> * [x]  [Puppeteer для краулинга страниц сайта и сохранения их в Markdown](https://web-standards.dev/articles/puppeteer-crawl-to-markdown/) `/articles/puppeteer-crawl-to-markdown/`
> * [x]  [JavaScript: топ тем и фреймворков для изучения в 2019 году](https://web-standards.dev/articles/top-themes-and-frameworks/) `/articles/top-themes-and-frameworks/`
> * [x]  [Та же история, только с CSS](https://web-standards.dev/articles/css-vs-js-same-story/) `/articles/css-vs-js-same-story/`
> * [x]  [Инклюзивные компоненты: переключатели](https://web-standards.dev/articles/toggle-buttons/) `/articles/toggle-buttons/`
> * [x]  [WebP сегодня: зачем и как?](https://web-standards.dev/articles/webp-today/) `/articles/webp-today/`
> * [x]  [Доступные SVG-иконки с инлайновыми спрайтами](https://web-standards.dev/articles/accessible-svg-icons/) `/articles/accessible-svg-icons/`
> * [x]  [Просто используйте стили для :focus, чёрт возьми](https://web-standards.dev/articles/just-use-focus/) `/articles/just-use-focus/`
> * [x]  [Полезные правила доступности, которые останутся в памяти](https://web-standards.dev/articles/pragmatic-a11y-rules/) `/articles/pragmatic-a11y-rules/`
> * [x]  [Важность уровней заголовков для вспомогательных технологий](https://web-standards.dev/articles/heading-levels/) `/articles/heading-levels/`
> * [ ]  [CSS: новый вид JavaScript](https://web-standards.dev/articles/css-new-kind-of-javascript/) `/articles/css-new-kind-of-javascript/`
> * [ ]  [Функции-декораторы, которые можно написать с нуля](https://web-standards.dev/articles/function-decorators/) `/articles/function-decorators/`
> * [ ]  [Глубокое погружение в ES-модули в картинках](https://web-standards.dev/articles/es-modules-cartoon-dive/) `/articles/es-modules-cartoon-dive/`
> * [ ]  [Руководство для прохождения интервью по фронтенду](https://web-standards.dev/articles/front-end-interview-handbook/) `/articles/front-end-interview-handbook/`
> * [ ]  [О доступности интерфейсов из первых уст](https://web-standards.dev/articles/a11y-users-interview/) `/articles/a11y-users-interview/`
> * [ ]  [Роутинг, бандлинг и ленивая загрузка на Webpack](https://web-standards.dev/articles/multiple-routes-webpack/) `/articles/multiple-routes-webpack/`
> * [ ]  [Промисы на примерах из жизни](https://web-standards.dev/articles/promises-explained/) `/articles/promises-explained/`
> * [ ]  [Сколько стоит JavaScript?](https://web-standards.dev/articles/the-cost-of-javascript/) `/articles/the-cost-of-javascript/`
> * [ ]  [Метрики загрузки страницы](https://web-standards.dev/articles/performance-metrics/) `/articles/performance-metrics/`
> * [ ]  [Генерация HTTP-запросов: Fetch или Axios.js](https://web-standards.dev/articles/fetch-vs-axios/) `/articles/fetch-vs-axios/`
> * [ ]  [Критический CSS + прогрессивный CSS = ?](https://web-standards.dev/articles/critical-and-progressive-css/) `/articles/critical-and-progressive-css/`
> * [ ]  [Как создать адаптивную сетку](https://web-standards.dev/articles/responsive-grid-system/) `/articles/responsive-grid-system/`
> * [ ]  [Невыполненные обещания веб-компонентов](https://web-standards.dev/articles/broken-promise-web-comps/) `/articles/broken-promise-web-comps/`
> * [ ]  [Реализуем пуш-уведомления на фронтенде и бэкенде](https://web-standards.dev/articles/push-front-back/) `/articles/push-front-back/`
> * [ ]  [Обещание бургерной вечеринки](https://web-standards.dev/articles/promise-burger-party/) `/articles/promise-burger-party/`
> * [ ]  [Манифест? А? Что? Зачем?](https://web-standards.dev/articles/manifest-what-why/) `/articles/manifest-what-why/`
> * [ ]  [Улучшение формы комментариев](https://web-standards.dev/articles/enhancing-comment-form/) `/articles/enhancing-comment-form/`

**Comment by Holiden** [comment]
Ещё:

> * [ ]  [CSS: новый вид JavaScript](https://web-standards.dev/articles/css-new-kind-of-javascript/) `/articles/css-new-kind-of-javascript/`
> * [ ]  [Функции-декораторы, которые можно написать с нуля](https://web-standards.dev/articles/function-decorators/) `/articles/function-decorators/`
> * [ ]  [Глубокое погружение в ES-модули в картинках](https://web-standards.dev/articles/es-modules-cartoon-dive/) `/articles/es-modules-cartoon-dive/`
> * [ ]  [Руководство для прохождения интервью по фронтенду](https://web-standards.dev/articles/front-end-interview-handbook/) `/articles/front-end-interview-handbook/`

**Comment by Holiden** [comment]
В общем, я доделаю)

**Comment by pepelsbey** [comment]
Ого!

**Comment by pepelsbey** [comment]
@Holiden может уже кинуть пулреквест? Например, с первыми четырьмя статьями. Просто если кинуть все 44, то его будет сложно ревьюить.

**Comment by Holiden** [comment]
> @Holiden может уже кинуть пулреквест? Например, с первыми четырьмя статьями. Просто если кинуть все 44, то его будет сложно ревьюить.

Сори, коммент прочитал после пуша(
