### ISSUE TITLE
Завести карточки всех людей, кто есть в статьях

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/nouvelle#237]
Сейчас [у некоторых статей](https://web-standards.dev/articles/introduction-to-variable-fonts/) если в md есть человек про перевод, но на него не заведена карточка, пишется пустой "Перевод" на странице, а надо либо просто текст без ссылки (если карточки нет), либо завести всем карточки со ссылками.

**Comment by pepelsbey** [comment]
Да, я думаю стоит разрешить карточки без ссылок и фоток.
