### ISSUE TITLE
Запретить в Stylelint писать rgb- и rgba-нотации цветов в пользу HEX

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/nouvelle#254]
Ну или обсудить и решить, что нужно иначе. Кажется, что HEX универсальнее.

**Comment by alkorlos** [comment]
В старом Edge не работает прозрачность в hex, если он уже не нужен то можно универсальности в стили добавить.

**Comment by Holiden** [comment]
В Edge и наши аватарки не работают :)

**Comment by pepelsbey** [comment]
> В старом Edge не работает прозрачность в hex

@alkorlos да, поэтому мы её плагином [превращаем](https://github.com/web-standards-ru/nouvelle/blob/master/gulpfile.js#L13) в rgba :)
