### ISSUE TITLE
Вертикальный скролл у блоков кода в Safari

### ISSUE THREAD

**Issue by misterblblbl** [web-standards-ru/nouvelle#263]
В Safari на ширине от 1200 до 1239 px у блоков кода появляется вертикальный скролл.
<img width="779" alt="Screenshot 2020-04-26 at 17 54 52" src="https://user-images.githubusercontent.com/12000927/80311231-266b9000-87e7-11ea-9e12-1f0f91267d76.png">

Пример можно найти вот здесь, последний блок кода в статье: [https://web-standards.dev/articles/speed-up-with-browserslist/](url)

Если изменять ширину окна, то скролл может пропадать, чтобы воспроизвести важно, чтобы ширина окна была в диапазоне 1200 — 1239 px.

**Comment by pepelsbey** [comment]
Поправили в #266, но перепроверь, пожалуйста.
