### ISSUE TITLE
Подумать над адаптацией под разную ширину блока «Читать дальше»

### ISSUE THREAD

**Issue by misterblblbl** [web-standards-ru/nouvelle#264]
Если открыть сайт с планшета (iPad mini) и долистать до блока с рекомендованными другими статья, разница в отступах по сторонам у текста статьи и у блока рекомендаций получается совсем небольшой и может выглядеть как ошибка в вёрстке:

![photo_2020-04-26 18 49 44](https://user-images.githubusercontent.com/12000927/80312789-0db3a800-87f0-11ea-9881-82c0fdf9b262.jpeg)

Возможно, стоит поменять поведение блока при различных ширинах окна.

**Comment by pepelsbey** [comment]
Вроде поправили, но перепроверь, пожалуйста :)
