### ISSUE TITLE
Найти и настроить линтер для маркдауна

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#36]
У нас очень много маркдауна. Например, все статьи строятся на нём. Нужно найти линтер и сделать команду `npm run md-lint`.

**Comment by pepelsbey** [comment]
См. [обсуждение](https://github.com/web-standards-ru/new/issues/61) в предыдущей итерации. Там есть предложения и подобности.

**Comment by pepelsbey** [comment]
В принципе, даже [пулреквест](https://github.com/web-standards-ru/new/pull/94/files) был, откуда можно скопировать файлы, завести и проверить.

**Comment by ratibordas** [comment]
Взял remark-lint из пуллреквеста, запускается через раз со стандартным пресетом. Буду разбираться. Подходит ли [конфиг](https://github.com/web-standards-ru/new/pull/94/files) или требуется доработка?

**Comment by pepelsbey** [comment]
Я бы взял этот конфиг, а потом бы настроил его по ходу. Главное, чтобы он начал показывать ошибки;
