### ISSUE TITLE
Главная страница. Врезка о конференции

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#39]
Родительская задача #1 похожый элемент — врезка о подкасте в #40

Сверстать врезку о конференции. Mobile-first

![01](https://user-images.githubusercontent.com/2804205/66548190-75065500-eb49-11e9-86bc-ada4a1e4b2a7.png)

## Мобильная версия
Блок двустрочный, текст не переносится и прокрутки тоже нет.

![image](https://user-images.githubusercontent.com/2804205/66555796-e816c800-eb57-11e9-89db-71b45f841b4c.png)

**Comment by pepelsbey** [comment]
Блок двустрочный, текст не переносится и прокрутки тоже нет.
