### ISSUE TITLE
Главная страница. Врезка о подкасте

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#40]
Родительская задача #1 похожый элемент — врезка о подкасте в #39

Сверстать врезку о подкасте. Mobile-first

![01](https://user-images.githubusercontent.com/2804205/66548190-75065500-eb49-11e9-86bc-ada4a1e4b2a7.png)

**Comment by higimo** [comment]
@ronuar правильно я понимаю, что ты просто верстаешь, а данные хардкодишь?

**Comment by ronuar** [comment]
Да, только верстаю
