### ISSUE TITLE
Главная страница. Свежие статьи

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#41]
Родительская задача #1

Есть наработки в #131 

Сверстать список свежих статей. Mobile-first

Список элементов:
- [ ] Название статьи
- [ ] Имя автора
- [ ] Дата публикации
- [ ] Текст анонса

![02](https://user-images.githubusercontent.com/2804205/66548191-75065500-eb49-11e9-915a-1c33babf25da.png)

**Comment by pepelsbey** [comment]
Фичеринг — это не просто попытка решить ситуацию с неудобным циклом, а вот прямо «фича», хотелось бы руками расставлять статьи на главую. Так что я за флаги в файлах.

Предлагаю следующий вариант: пройтись по циклу из статей и вывести все последние (белые карточки) в порядке убывания даты, если у них нет флага `featured`. А перед этим поставить любую статью из цикла, у которой есть `featured`.

<img width="1198" alt="Screen Shot 2019-11-18 at 12 43 02" src="https://user-images.githubusercontent.com/105274/69041842-4198cf00-0a01-11ea-9331-5430632f9d76.png">

**Comment by PsarewIvan** [comment]
@pepelsbey , могу написать стили для `featured `статьи, тем более похожие я уже делал для карточки стать. 
Флаг `featured `нужно будет проставить в .md файле каждой статьи?

**Comment by pepelsbey** [comment]
@PsarewIvan давай! Ключ `featured: true` нужно проставить одной статье и тогда у неё станет тёмный фон. Остальные выбираются по принципу `latest && !featured` (псевдокод).
