### ISSUE TITLE
Карточка статьи. Прикрепить вёрстку шапки

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#51]
Родительская задача #3

У нас уже свёрстана шапка из #37 нужно инклюдить её и в этот шаблон

**Comment by pepelsbey** [comment]
Я кажется не понимаю, о чём это задача. Картинку бы или объяснить.

**Comment by higimo** [comment]
@pepelsbey заинклюдить шапку в 11ty. Кажется, это задача выполнена

**Comment by pepelsbey** [comment]
А, круто
