### ISSUE TITLE
Карточка статьи. Обложка, название, теги, дата статьи

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#52]
Родительская задача #3

У нас есть много информации про статьи — все их нужно сверстать в шаблон так, чтобы статьи, где этой информации нет ничего не ломалось.

![01](https://user-images.githubusercontent.com/2804205/66662193-0f04f500-ec51-11e9-8e8a-176c00e23861.png)

**Comment by PsarewIvan** [comment]
В работе в #76. Добавьте меня в Assignees, пожалуйста

**Comment by PsarewIvan** [comment]
@vsesvitlo я случайно себя убрал из assigned :) добавьте, пожалуйста, еще раз

**Comment by pepelsbey** [comment]
Сделали в #76 #111 и где-то ещё
