### ISSUE TITLE
Карточка статьи. Блок авторов и соавторов

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#53]
Родительская задача #3

У нас указаны авторы и его помощники, редакторы и прочие роли ответственных людей, никого забывать нельзя и нужно иметь возможность указывать рандомные слова в роли человека. Роль и имя может быть настолько длинными, что займут две строки (например, «Переводчик с английского и корректор»).

![02](https://user-images.githubusercontent.com/2804205/66662194-0f04f500-ec51-11e9-9a36-ab4d015e4f1f.png)

**Comment by PsarewIvan** [comment]
В работе #76. Добавьте в Assignees, пожалуйста

**Comment by higimo** [comment]
@PsarewIvan упоминайте ники — так придёт уведомление

**Comment by PsarewIvan** [comment]
@pepelsbey , есть два вопроса: 
- откуда будут браться картинки для аватарок, и нужно ли включать их в семантику или делать псевдоэлементами?
- и главное, сам блок размещается слева от текста статьи, пока в статье текст - проблем нет. Проблемы могут возникнуть, если в статье вначале будет картинка, которая растягивается на всю ширину родительского блока. В этом случае блок с авторами может "уйти" под картинку из статьи. Единственное, что мне приходит в голову - это использовать JS.
Есть ли идеи, как это сделать на CSS?

**Comment by pepelsbey** [comment]
1. Картинки для аватарок будем хранить для всех авторов в отдельной папке — нужна отдельная задача для этого, @higimo сделаешь? :) Вставлять будем как `<img>` и поверх рисовать шейпу с фильтром.
2. Картинка на всю ширину будет «не разрешена», мы всё-таки сами будем статьи писать и поймём, если что-то накладывается, это же не какой-то случайный генератор.

**Comment by higimo** [comment]
@pepelsbey можешь подробнее описать структуру папок? Я пока себе очень плохо представляю. Вероятно, это `/img/authors/sitnik/medium.jpg`?

**Comment by pepelsbey** [comment]
Я бы пока сделал `src/authors/andrey-sitnik.jpg` и дальше уже посмотрим, как это развить.

**Comment by higimo** [comment]
@pepelsbey теперь напрашиваются страницы авторов=) завёл #108

**Comment by pepelsbey** [comment]
Я пока придержал лошадей и остановился на фотках. Но да — страница автора может кому-то дать повод писать и переводить для «Веб-стандартов».

**Comment by pepelsbey** [comment]
Сделали где-то там по разным пулреквестам
