### ISSUE TITLE
Карточка статьи. Текст статьи

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#54]
Родительская задача #3

Встатье может быть цитата, кусок кода (хайлайт на код важен), ссылки прямо в тексте, (не)нумерованные списки, картинки на весь формат, картинки в ширину колонки и картинки с обтеканием справа-слева. У каждой картинки может быть подпись.

![all](https://user-images.githubusercontent.com/2804205/62827097-50394400-bbd1-11e9-9cea-198814ed5dc4.png)

**Comment by vsesvitlo** [comment]
Работаю над задачей

**Comment by pepelsbey** [comment]
@vsesvitlo привет! Как успехи, есть какая-то основа для пулреквеста? Если есть — покажите, если нет — отпустите задачу, может кто-то ещё возьмётся.

**Comment by vsesvitlo** [comment]
> @vsesvitlo привет! Как успехи, есть какая-то основа для пулреквеста? Если есть — покажите, если нет — отпустите задачу, может кто-то ещё возьмётся.

Привет! Смогу показать что сделала примерно через 4 часа.

**Comment by higimo** [comment]
@vsesvitlo 4 часа прошло, есть успех?

**Comment by higimo** [comment]
@vsesvitlo если вам нужна помощь просто с гитом разобраться напишите в чатик — решим любой вопрос, не стесняйтесь. Не хотелось бы терять ваш прогресс.

**Comment by vsesvitlo** [comment]
> @vsesvitlo если вам нужна помощь просто с гитом разобраться напишите в чатик — решим любой вопрос, не стесняйтесь. Не хотелось бы терять ваш прогресс.

Сейчас покажу, что есть: не подключила картинки и не все стили ещё готовы, но на гридах сетку сделала, адаптивность также.
С гитом попробую разобраться, если что, напишу вопрос

**Comment by vsesvitlo** [comment]
Закоммитила то, что сейчас готово.
Прошу прощения, что занянула по времени, при переносе данных в гит выяснила нюансы, на которые сразу не обратила внимание (вносила правки не в тех файлах). Сейчас вроде бы разобралась. Завтра продолжу

**Comment by pepelsbey** [comment]
> Закоммитила то, что сейчас готово.

Спасибо! Сделайте из этого пулреквест и давайте уже там продолжим :)

**Comment by vsesvitlo** [comment]
Сделала пулреквест.
Ранее не работала с файлами формата .njk, верстку до этого делала, используя html и css.
Готова исправить

**Comment by pepelsbey** [comment]
Работа идёт в #109

**Comment by wspwebben** [comment]
Раз задача освободилась, займусь ей

**Comment by higimo** [comment]
@wspwebben поставил ответсвенным

**Comment by wspwebben** [comment]
![image](https://user-images.githubusercontent.com/34203719/69475418-5b6e5380-0dff-11ea-9a1d-972dabcaf41d.png)

Не могу найти статью с примером разметки подобной выноски
Это просто h3 с картинкой?

**Comment by pepelsbey** [comment]
@wspwebben, предлагаю сделать это так:

```html
<figure>
    <img>
    <figcaption>
        Заголовок выноски
        <small>Заголовок выноски</small>
    </figcaption>
</figure>
```

**Comment by alkorlos** [comment]
Добрый день.
Нужна помощь с этой задачей?
Может, если с ней столько сложностей, разбить её на две подзадачи? Отдельная задача для тэгов в content.css и отдельная для картинок и блоков в media.css?

**Comment by pepelsbey** [comment]
Я вмёржу [существующий пулреквест](https://github.com/web-standards-ru/nouvelle/pull/128) и заведу задачу с его правками.

**Comment by higimo** [comment]
Закрою, но ожидаем задач от @pepelsbey
