### ISSUE TITLE
Карточка статьи. Статьи по теме

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#55]
Родительская задача #3

Хорошо бы указывать эту информацию в каких-то мета-данных.

![10](https://user-images.githubusercontent.com/2804205/66662204-10ceb880-ec51-11e9-9f8c-2726c3bed23b.png)

**Comment by PsarewIvan** [comment]
@higimo , @pepelsbey , добавьте меня в assigned, пожалуйста :)

**Comment by PsarewIvan** [comment]
@pepelsbey , количество статей ведь может быть произвольного количества, от 0 и до условной бесконечности, или будет показываться определенное количество?
Как их будем центрировать на широких разрешениях?

**Comment by pepelsbey** [comment]
Количество статей предлагаю ограничить тремя и тянуть их до максимальной ширины макета. Это прямо сейчас, по макету — потом подберём количество и пропорции по ситуации.
