### ISSUE TITLE
Карточка статьи. Ссылка на конференцию

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#56]
Родительская задача #3

Иногда бывают конференции, нужно показать ссылку на неё.

![11](https://user-images.githubusercontent.com/2804205/66662205-10ceb880-ec51-11e9-86f0-e535e9618215.png)

**Comment by PsarewIvan** [comment]
@higimo , @pepelsbey , готов реализовать задачу, вроде тут ничего сложного :)
Есть вопросы:
- ссылка будет на ближайшую конференцию? и откуда будет подтягиваться информация о конференции?
- может как-то подтягивать конференцию из #140 ?
- судя по макету, как я понял, имеется ссылка на конференцию на страницах Article и Articles перед футером: 
![image](https://user-images.githubusercontent.com/28845333/69865135-7a625f00-12b1-11ea-96c3-ee396bb26f7f.png)
и ссылка на конференцию на главной, сразу после шапки:
![image](https://user-images.githubusercontent.com/28845333/69865177-9108b600-12b1-11ea-9760-fffe4a78fffa.png)
это будет одна и та же ссылка, или тут будут разные конференции? Если одна и та же, то лучше, наверное, сделать ее одним компонентом и изменять стили в зависимости от расположения?

**Comment by pepelsbey** [comment]
Я бы для большей безопасности просто сделал контентный файл, который бы выводил бы здесь. Например, `conference.md`, в котором в YAML-полях дата и те самые две строки.

**Comment by pepelsbey** [comment]
Это всё потому, что конференция в итоге будет интегрироваться в сайт и не хочется заклыдываться в импорт данных с сайта, который закроется.

**Comment by PsarewIvan** [comment]
А "вторая строка" - это что такое? :)

**Comment by pepelsbey** [comment]
Ну, любой текст с описанием конференции, туда можно забить любой текст пока.

**Comment by PsarewIvan** [comment]
@pepelsbey , по поводу моего вопроса выше: ссылка на конференцию на главной в шапке (и вообще ссылка ли это?) и ссылка на конференцию на других страницах перед футером - это одна и та же ссылка, или разные?

**Comment by pepelsbey** [comment]
Да, все информеры в шапке — ссылки. Они там для того, чтобы быстро перейти к новому. И в подвале та же самая ссылка, да.
