### ISSUE TITLE
Карточка статьи. Прикрепить вёрстку футера

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#57]
Родительская задача #3

У нас уже свёрстан футер в #44 нужно инклюдить её и в этот шаблон

**Comment by PsarewIvan** [comment]
Не хотел бы показаться занудой, но *ПрикрЕпить =)

**Comment by pepelsbey** [comment]
@PsarewIvan поправил, спасибо :)

**Comment by higimo** [comment]
https://github.com/web-standards-ru/nouvelle/commit/477e62ccd9158850dfa937082780068e8fbbe499
