### ISSUE TITLE
Завести систему тегов в статьях

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#6]
Теги — сквозная навигация на сайте. Кликнув по тегу в статье, попадаешь на отдельную страницу, где показаны все статьи с таким тегом.

Теги в общем случае должны быть существительным в именительном падеже. Тег нужно заводить к новому-перспективному явлению, где ожидается ещё несколько статей. Теги, присваиваемые лишь для одной статьи не приветствуются.

- [x] Сейчас не продуманы такие элементы:
- [x] Дизайн урлов (предположительно `/articles/tags/%tag-name%`).
- [x] Дизайн страницы тега (вероятно, аналогично списку всех статьей).
- [x] Система назначения и именования тегов к статьям.
  - [x] Раздать всем статьям полный список тегов.

## Список тегов
- html
- css
- js
- svg
- a11y
- design
- performance
- typography

**Comment by higimo** [comment]
Я посмотрел статьи и выделил в них ключевые слова в начальной форме.

**Инклюзивные компоненты: тултипы и тоглтипы**
- Инклюзивные компоненты, компонент, тултип, подсказка, атрибут, ариа-атрибут, инклюзивность, скринридер, уведомление, взаимодействие, атрибут-роль, кнопка, ошибка

**Инклюзивные компоненты: меню и кнопки меню**
- Инклюзивные компоненты, компонент, инклюзивность, меню, дизайн, навигация, список, оглавление, атрибут, атрибут-роль, кнопка

**Всё, что нужно знать про ARIA Live Regions**
- роль, алерт, атрибут, ариа-атрибут, дизайн

**Советы по доступности интерактивных элементов на мобильных устройствах**
- доступность, WCAG, интерфейс, дизайн, кнопка, атрибут

Какие отфильтровываем, как избыточные? @pepelsbey

**Comment by pepelsbey** [comment]
Я бы завёл теги короткие, строчными и латиницей, плюс с фиксированным словарём, который медленно растёт. Как список HTML-тегов в спецификации :)

html, css, js, svg, a11y, design, performance, typography, …

**Comment by pepelsbey** [comment]
Кстати, система тегов была [на старом сайте](https://web-standards.ru/):

![image](https://user-images.githubusercontent.com/105274/66417608-0fab4a80-ea09-11e9-86ad-a20944c2be9e.png)

**Comment by higimo** [comment]
Сократил словарь. @pepelsbey что скажешь?

**Инклюзивные компоненты: тултипы и тоглтипы**
- a11y, component, css, html, inclusive

**Инклюзивные компоненты: меню и кнопки меню**
- a11y, component, css, js, html, inclusive

**Всё, что нужно знать про ARIA Live Regions**
- a11y, css, js, html

**Советы по доступности интерактивных элементов на мобильных устройствах**
- a11y, component, css, html

**Comment by pepelsbey** [comment]
Хм, component и inclusive слишком узкие, как по мне.

Предлагаю начать с этого и дальше расширять по живым примерам:

- html
- css
- js
- svg
- a11y
- design
- performance
- typography

**Comment by higimo** [comment]
Хорошо, список есть, добавил его в задачу. Осталось найти молодца, что справится с такой задачей.

**Comment by albertmolodec** [comment]
Хочу попробовать. Смогу активно заняться в эти выходные.

**Comment by pepelsbey** [comment]
@albertmolodec, а вы сможете только заполнить их статьям или ещё вывести? Задача из двух частей :)

**Comment by albertmolodec** [comment]
@pepelsbey 

И то, и то.

Прочитаю статьи, которые сейчас есть, проставлю им теги. 

Дальше, насколько я понял, нужно выводить их внутри каждой статьи. 
Вроде такого:

![image](https://user-images.githubusercontent.com/26366132/66989452-10a93f80-f0cd-11e9-9f08-78cafac7de09.png)


Когда кликаем на тэг, переходим на страницу со всеми статьями, содержащими тэг.

P.S. Судя по [комментарию](https://github.com/web-standards-ru/nouvelle/issues/6#issuecomment-540446268), мой никнейм идеально подходит для того, чтобы заняться этой задачей :)

**Comment by pepelsbey** [comment]
Артур, вы с этой задачей созданы друг для друга :D Если будут вопросы, пишите здесь или могу добавить в чат в Телеграме.
