### ISSUE TITLE
Продумать и внедрить систему работы JS на сайте

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#71]
Рано или поздно нам понадобится что-то на JS сделать. В идеале это должны быть минимальные файлы, расширяемые и понятные. JS нужен для динамизации контента, верстаем на 11ty.

Нужно продумать сборку, архитектуру и подключение. Результат в комменты, потом оформим отдельным файликом, типа ридми.

**Comment by lBeJIuk** [comment]
Как вы смотрите на добавление prettier и\или eslint?

**Comment by pepelsbey** [comment]
Prettier не надо, а ESLint вполне :)

**Comment by higimo** [comment]
@pepelsbey можешь обозначить, какие задачи мы будем решать через JS?

**Comment by pepelsbey** [comment]
У нас есть два типа JS:

1. Для сборки сайта
2. Для работы на сайте

Эта задача для второго типа. Где нам сейчас понадобятся скрипты:

- Для открытия-закрытия меню
- Для разворачивания списка со статьями, если он станет слишком длинными (60+)

Каждый из скриптов я бы оформил модулем, положил рядом с блоком или в отдельную папку скриптов. Дальше подключил бы и собрал в ES5. Но это как раз суть этой задачи — придумать, как лучше.

**Comment by ogonkov** [comment]
Я бы предложил компонентный подход, когда всё относящееся к компоненту/блоку лежит в своей папке

```
`- src
   |- pages
   `- components
      |- navigation
      |  |- index.js
      |  |- navigation.njk
      |  `- navigation.css
      `- footer
         `- footer.njk
```

Имена файлов в примере выше условные, все совпадения с реальными файлами случайны.

Плюсы:
* всё лежит рядом
* правка стилей, в условиях когда css-модули признаны "усложнением", становитя немного проще
* при код-ревью сразу видно если стили поменялись а шаблон или js нет
* можно делать несколько шаблонов, js, css, логично объединяя их в компоненте

Минусы:
* Не обнаружено

**Comment by pepelsbey** [comment]
@ogonkov мне нравится, как это выглядит, но я бы предложил отложить рефакторинг до момента запуска. А сейчас можно попробовать сделать пулреквест, в котором поработать над реализацией этого подхода. Сходу кажется, что будет сложновато это собирать: как с точки зрения 11ty, так и ресурсов. Но может быть я не прав.

**Comment by ogonkov** [comment]
Структура файлов никак не связана с 11ty

**Comment by pepelsbey** [comment]
А откуда тогда возьмутся обработчики footer.njk?

**Comment by ogonkov** [comment]
Какие обработчики? Шаблон для интерфейсного компонента просто импортируется и используется в нужном месте

**Comment by higimo** [comment]
@ogonkov выглядит клёво. Если я правильно понял нужен сборщик css и js?

Это особенный кайф. Никогда такого аргумента не встречал, хотя он должен быть главным.
> при код-ревью сразу видно если стили поменялись а шаблон или js нет

**Comment by ogonkov** [comment]
Сборщик не нужен

**Comment by pepelsbey** [comment]
Мне кажется, нам здесь нужно остановиться и перестать обсуждать то, что ещё не работает :) Мы все согласились, что выглядит мило. Осталось понять, насколько это жизнеспособно. Но, повторюсь, очень не хочется, чтобы это помешало запуску.

Более того, если хочется помочь делу, лучше помочь с запуском :) А потом рефакторить сколько угодно. Там много интересных задач: интеграция подкаста, календаря, конференции и кучи всего.

**Comment by ogonkov** [comment]
> много интересных задач

осталось только нормально их описать)

**Comment by higimo** [comment]
@ogonkov всё, что не понятно вы можете спросить внутри соответствующей таски. До этого момента (включая эту задачу) у вас затруднений не обнаружилось.

**Comment by pepelsbey** [comment]
У нас появилась сборка JS, которая берёт всё из одного файла. Будем расти — придумаем систему сложнее :) Пока закрываю.
