### ISSUE TITLE
Отступы в Preview статьи

### ISSUE THREAD

**Issue by Holiden** [web-standards-ru/nouvelle#79]
При вёрстке #64 обнаружены разные отступы в превью статьи. Может стоит принять единый отступ равный 16px?
![1](https://user-images.githubusercontent.com/48956742/67059790-950ac980-f184-11e9-9a76-fcdc37df5008.jpg)

**Comment by Holiden** [comment]
Так же и нижние отступы. 
![1](https://user-images.githubusercontent.com/48956742/67062246-f6369b00-f18c-11e9-980c-6fcba9d232cf.jpg)
![2](https://user-images.githubusercontent.com/48956742/67062247-f6369b00-f18c-11e9-90c3-160de709efd9.jpg)

**Comment by pepelsbey** [comment]
Разные отступы визуально выравнивают блоки разной тяжести по горизонтальной оси. Делать везде одинаковые отступы не нужно. Что касается широкой и узкой карточки — меняющиеся отступы — это адаптация.
