### ISSUE TITLE
Реализовать динамические формы для аватарок авторов

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#86]
Предполагаем, что это можно сделать на SVG-масках, но иной способ не осуждается.

При выводе обычной цветной фотки нужно превращать её в особый вид, как на макете:
![image](https://user-images.githubusercontent.com/2804205/67383003-17392a80-f597-11e9-9f5a-ccbe59d02d7c.png)

**Comment by albertmolodec** [comment]
Сегодня читал, как сделать случайно генерируемую SVG-маску.
Нашел [библиотеку](https://blobs.dev/), которая может помочь с этим. В качестве генератора псевдослучайности может использоваться имя автора.

![Screenshot_20191023_132949](https://user-images.githubusercontent.com/26366132/67384148-4d77a980-f599-11e9-8e44-262892c78e0c.png)
![Screenshot_20191023_133008](https://user-images.githubusercontent.com/26366132/67384149-4e104000-f599-11e9-8ead-114408987c8a.png)

Пробовал сделать демку на codepen'е, но заступорился, когда нужно сделать маску. 
Если у кого-нибудь есть опыт в SVG масках, предлагаю форкнуть и добить: https://codepen.io/albertmolodec/pen/QWWpEmV

**Comment by pepelsbey** [comment]
А нужно ли нам генерировать уникальную маску для каждого автора? Я думаю, что можно сделать штук пять, замиксовать это с тремя цветами с макета и получится очень неплохое разнообразие. Это точно лучше, чем в рантайме крутить библиотеку.

**Comment by higimo** [comment]
@pepelsbey 7*4 лучше, чем 5*3=)

**Comment by pepelsbey** [comment]
@yoksel можешь нам помочь сделать такие штуки для авторов? Кажется это твой профиль :)

**Comment by yoksel** [comment]
Недавно делала доклад ровно про это : )
https://yoksel.github.io/non-square-web/

Мне тоже больше нравится идея готового набора масок, чем генерировать каждый раз.  Внешние SVG-маски поддерживаются хуже, чем если их заинлайнить (тогда они будут работать просто как маска из картинки). Ещё более простой вариант — использовать SVG clip-path через CSS, он поддерживается лучше. Если нужно, чтобы работало везде включая IE, тогда лучше завернуть картинки и маски в SVG

Сделала пример с маской и с clip-path: https://codepen.io/yoksel/pen/JjjmOLB. 

clip-path получил относительные координаты (с помощью https://yoksel.github.io/relative-clip-path/) и тянется на весь элемент, это избавляет от необходимости подгонять путь под размер элемента

**Comment by pepelsbey** [comment]
@yoksel а будет время сделать пулреквест? Можно в images положить несколько тестовых фоточек, вставить их в шаблоны при выводе статей с разными классами-масками. Ну или если ты сможешь только сами маски сделать, то тоже спасибо :)
