### ISSUE TITLE
Сделать компонент вывода мета-данных статьи

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/nouvelle#87]
- [ ] Автор(ы), если указаны
- [ ] Редактор(ы), если указаны
- [ ] Оригинал(ы), если указаны

Мета-данные уже почистил @pepelsbey https://github.com/web-standards-ru/nouvelle/pull/85/files

Если есть source, значит это перевод. Если автора, переводчика, редактора больше одного, то вывести через запятую.

**Comment by albertmolodec** [comment]
Хочу взять задачу себе ✋

**Comment by pepelsbey** [comment]
@albertmolodec отлично :) Кстати, ссылки тоже может не быть. И прежде, чем писать код, можно порисёрчить и здесь обсудить, как это будет работать.
